---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint -c molecule/yaml-lint.yml .
  ansible-lint -c molecule/ansible-lint.yml .
  flake8
platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-rockylinux8}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    exposed_ports:
      - 7474/tcp
      - 7687/tcp
    published_ports:
      - 0.0.0.0:7474:7474/tcp
      - 0.0.0.0:7687:7687/tcp
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  log: false
  options:
    vvv: false
scenario:
  name: default
verifier:
  name: ansible
